name: Main CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            cmake-preset: ninja-linux-apt
          - os: windows-latest
            cmake-preset: vs2019-windows-vcpkg

    steps:
      - uses: actions/checkout@v2
        with:
          path: bsa
          submodules: 'true'

      - name: Setup Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "CC=gcc-10" >> $GITHUB_ENV
          echo "CXX=g++-10" >> $GITHUB_ENV

          wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
          unzip ninja-linux.zip
          sudo mv ninja /usr/local/bin

          sudo apt install zlib1g-dev liblz4-dev -y

      - name: Setup vcpkg
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          ${{ env.VCPKG_INSTALLATION_ROOT }}/bootstrap-vcpkg.bat
          vcpkg --version >> vcpkg-version.txt

      - name: Cache vcpkg
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/cache@v2
        id: vcpkg-cache
        env:
          cache-name: vcpkg-cache
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}/*
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bsa/**/vcpkg.json', 'vcpkg-version.txt') }}

      - name: Configure CMake
        run: cmake --preset ${{ matrix.cmake-preset }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBSA_BUILD_DOCS=OFF ${{ github.workspace }}/bsa

      - name: Build
        run: cmake --build ${{ github.workspace }}/bsa/build

      - name: Test
        working-directory: ${{ github.workspace }}/bsa/build
        run: ctest -C ${{ env.BUILD_TYPE }} -V
