name: Main CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

env:
  BUILD_TYPE: Debug
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-archives

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake-generator: ninja
            cmake-platform: linux
            setup: bash scripts/setup.sh
          - os: windows-latest
            cmake-generator: vs2019
            cmake-platform: windows
            setup: '' # nothing right now

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Run setup script
        run: ${{ matrix.setup }}

      - name: Create vcpkg binary cache folder
        run: mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

      - name: Cache vcpkg archives
        uses: actions/cache@v2
        env:
          cache-name: vcpkg-cache
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake --preset ${{ matrix.cmake-generator }}-${{ matrix.cmake-platform }}-vcpkg -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }} -V
